//REQUEST LOGIN USER  REQUEST 
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
//IF SUCCESS RETURN  LOGIN USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
//RETURN ERROR  LOGIN USER
export const LOGIN_FAIL = 'LOGIN_FAIL'


//REQUEST REGISTER USER REQUEST
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
//IF SUCCESS  RETURN  REGISTER USER
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
//RETURN ERROR  REGISTER USER
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'


//REQUEST LOAD USER PAGE REQUEST
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
//IF SUCCESS  RETURN  LOAD USER PAGE
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
//RETURN ERROR  LOAD USER PAGE
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

//UPDATE PROFILE 
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

//REQUEST UPDATE PASSWORD
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
//IF SUCCESS  RETURN PASSWORD UPDATE
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
//RETURN rest password update
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
//RETURN UPDATE PASSWORD ERROR 
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

//REQUEST  FORGOT PASSWORD 
export const FORGOT_PASSWORD_REQUEST ='FORGOT_PASSWORD_REQUEST'
//IF SUCCESS RETURN FORGOT PASSWORD SUCCESS 
export const  FORGOT_PASSWORD_SUCCESS ='FORGOT_PASSWORD_SUCCESS'
//RETURN ERROR FORGOT PASSWORD 
export const  FORGOT_PASSWORD_FAIL ='FORGOT_PASSWORD_FAIL'


//REQUEST  NEW PASSWORD 
export const NEW_PASSWORD_REQUEST ='NEW_PASSWORD_REQUEST'
//IF SUCCESS RETURN NEW PASSWORD SUCCESS 
export const  NEW_PASSWORD_SUCCESS ='NEW_PASSWORD_SUCCESS'
//RETURN ERROR NEW PASSWORD 
export const  NEW_PASSWORD_FAIL ='NEW_PASSWORD_FAIL'



//ALL USER (ADMIN DASHBOARD)
export const  ALL_USERS_REQUEST ='ALL_USERS_REQUEST'
export const  ALL_USERS_SUCCESS ='ALL_USERS_SUCCESS'
export const  ALL_USERS_FAIL ='ALL_USERS_FAIL'

//UPDATE USER (ADMIN DASHBOARD)
export const  UPDATE_USER_REQUEST ='UPDATE_USERS_REQUEST'
export const  UPDATE_USER_SUCCESS ='UPDATE_USERS_SUCCESS'
export const  UPDATE_USER_RESET = 'UPDATE_USERS_RESET'
export const  UPDATE_USER_FAIL ='UPDATE_USERS_FAIL'

//USER DETAILS (ADMIN DASHBOARD)
export const  USER_DETAILS_REQUEST ='USER_DETAILS_REQUEST'
export const  USER_DETAILS_SUCCESS ='USER_DETAILS_SUCCESS'
export const  USER_DETAILS_FAIL ='USER_DETAILS_FAIL'

//UPDATE USER (ADMIN DASHBOARD)
export const  DELETE_USER_REQUEST ='DELETE_USERS_REQUEST'
export const  DELETE_USER_SUCCESS ='DELETE_USERS_SUCCESS'
export const  DELETE_USER_RESET = 'DELETE_USERS_RESET'
export const  DELETE_USER_FAIL ='DELETE_USERS_FAIL'


//IF SUCCESS LOGOUT USER
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
//RETURN ERROR MESSAGE
export const LOGOUT_FAIL = 'LOGOUT_FAIL'


/* ***************** DELEATE  ALL ERROR USER *************** */
//DELEATE  ALL ERROR USER
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


